=== mhfsudo/webapp/xml/school.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <!-- Ihre LÃ¶sung hier -->
    <xsd:element name="School">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Departments" type="Departments" maxOccurs="unbounded" minOccurs="1"/>
                <xsd:element name="Modules" type="Modules" maxOccurs="unbounded" minOccurs="1"/>
                <xsd:element name="Lecturers" type="Lecturers" maxOccurs="unbounded" minOccurs="1"/>
                <xsd:element name="Students" type="Students" maxOccurs="unbounded" minOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Departments">
        <xsd:sequence>
            <xsd:element name="Department1">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Department2">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Modules">
        <xsd:sequence>
            <xsd:element name="Module1">
                <xsd:complexType>
                    <xsd:choice>
                        <xsd:element name="ModuleName" type="xsd:string"/>
                    </xsd:choice>
                    <xsd:attribute name="code" type="xsd:string"/>
                    <xsd:attribute name="departments" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Module2">
                <xsd:complexType>
                    <xsd:choice>
                        <xsd:element name="ModuleName" type="xsd:string"/>
                    </xsd:choice>
                    <xsd:attribute name="code" type="xsd:string"/>
                    <xsd:attribute name="departments" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Module3">
                <xsd:complexType>
                    <xsd:choice>
                        <xsd:element name="ModuleName" type="xsd:string"/>
                    </xsd:choice>
                    <xsd:attribute name="code" type="xsd:string"/>
                    <xsd:attribute name="departments" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Lecturers">
        <xsd:sequence>
            <xsd:element name="Lecturer">
                <xsd:complexType>
                    <xsd:group ref="Person"/>
                    <xsd:attribute name="gender" type="xsd:string"/>
                    <xsd:attribute name="modules" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Students">
        <xsd:sequence>
            <xsd:element name="Student1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:group ref="Person"/>
                        <xsd:element ref="Exams"/>
                    </xsd:sequence>
                    <xsd:attribute name="gender" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Student2">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:group ref="Person"/>
                    </xsd:sequence>
                    <xsd:attribute name="gender" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Exams">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Exam1">
                    <xsd:complexType>
                        <xsd:attribute name="module" type="xsd:string"/>
                        <xsd:attribute name="date" type="xsd:date"/>
                        <xsd:attribute name="grade" type="xsd:int"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Exam2">
                    <xsd:complexType>
                        <xsd:attribute name="module" type="xsd:string"/>
                        <xsd:attribute name="date" type="xsd:date"/>
                        <xsd:attribute name="grade" type="xsd:int"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:group name="Person">
        <xsd:sequence>
            <xsd:element name="LastName" type="xsd:string"/>
            <xsd:element name="FirstName" type="xsd:string"/>
            <xsd:element name="Street" type="xsd:string"/>
            <xsd:element name="ZIP" type="xsd:int"/>
            <xsd:element name="City" type="xsd:string"/>
            <xsd:element name="AHVNumber" type="xsd:string"/>
            <xsd:element name="BirthDate" type="xsd:date"/>
        </xsd:sequence>
    </xsd:group>
</xsd:schema>

=== mhfsudo/webapp/xml/school.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<School xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="school.xsd">
    <Departments>
        <Department1 id="IT"/>
        <Department2 id="EL"/>
    </Departments>
    <Modules>
        <Module1 code="WebG" departments="IT">
            <ModuleName>Web-Grundlagen</ModuleName>
        </Module1>
        <Module2 code="OOP" departments="IT">
            <ModuleName>Objektoriente Programmierung</ModuleName>
        </Module2>
        <Module3 code="EL1" departments="IT EL">
            <ModuleName>Elektrotechnik I</ModuleName>
        </Module3>
    </Modules>
    <Lecturers>
        <Lecturer gender="m" modules="WebG OOP">
            <LastName>Keller</LastName>
            <FirstName>Peter</FirstName>
            <Street>Meine Strasse 3</Street>
            <ZIP>8001</ZIP>
            <City>Zurich</City>
            <AHVNumber>123.4567.8901.23</AHVNumber>
            <BirthDate>1982-01-01</BirthDate>
        </Lecturer>
    </Lecturers>
    <Students>
        <Student1 gender="m">
            <LastName>Meier</LastName>
            <FirstName>Hans</FirstName>
            <Street>Musterstrasse 3</Street>
            <ZIP>8001</ZIP>
            <City>Zurich</City>
            <AHVNumber>123.4567.8901.24</AHVNumber>
            <BirthDate>1990-01-01</BirthDate>
            <Exams>
                <Exam1 module="OOP" date="2016-01-01" grade="4"/>
                <Exam2 module="WebG" date="2016-01-02" grade="5"/>
            </Exams>
        </Student1>
        <Student2 gender="f">
            <LastName>MÃ¼ller</LastName>
            <FirstName>Doris</FirstName>
            <Street>Meine Strasse 4</Street>
            <ZIP>8001</ZIP>
            <City>Zurich</City>
            <AHVNumber>123.4567.8901.25</AHVNumber>
            <BirthDate>1990-01-02</BirthDate>
        </Student2>
    </Students>
</School>
